### ISSUE TITLE
patching of ebuilds

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [allenh1/superflore#2]
Since the `EAPI` now is 6, we should use `eapply` (remember the `eapply_user`) instead of `epatch` and we must do it in the `src_prepare` phase (not in `src_unpack`).
see https://devmanual.gentoo.org/ebuild-writing/eapi/

**Comment by allenh1** [comment]
Got it. Will do.

**Comment by allenh1** [comment]
Closing, as CMake-utils should handle this.
