### ISSUE TITLE
sanitize strings

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [allenh1/superflore#3]
To avoid this -> https://github.com/ros/ros-overlay/blob/master/ros-indigo/network_control_tests/network_control_tests-1.0.11.ebuild#L6

strings must be sanitized by removing/replacing/escaping `"` character

**Comment by allenh1** [comment]
Will do.

**Comment by Alessandro-Barbieri** [comment]
use `shlex.quote(string)`

**Comment by allenh1** [comment]
@Alessandro-Barbieri The point of this is not to execute it, as it's just crap that somehow made it into the string.

```py
string = string.replace('"', '')
```
should suffice.

**Comment by allenh1** [comment]
The proposed fix was, unfortunately, insufficient. I think the `.replace` strategy can be effective, so long as we are careful as to what we use. It's probably best to just restrict the input to only alphanumeric characters, and, if it's not an alphanumeric, it gets removed.

**Comment by Alessandro-Barbieri** [comment]
I found this https://docs.python.org/3/library/re.html#re.escape

**Comment by allenh1** [comment]
That looks like a much better way to do it. Would you like to do the honors? I restored your previous branch for you.

**Comment by Alessandro-Barbieri** [comment]
yes, but is only available in python3

**Comment by allenh1** [comment]
Well, that's unfortunate. I suppose .replace is still our friend, then.

Maybe something like this would suffice.

```py
def sanitize_string(string, legal_chars):
    ret = str()
    for c in string:
        if c in legal_chars:
            ret.append(c)
    return ret
```

**Comment by Alessandro-Barbieri** [comment]
Why not write the code only for python3? All machines have it now.

**Comment by allenh1** [comment]
I'd much rather the code function for python 2 and python 3 than just for python 3.

**Comment by Alessandro-Barbieri** [comment]
```python
def sanitize_string(string):
    ret = str()
    for c in string:
        if c in '()[]{}?*+-|^$\\.#\t\n\r\v\f\'\"':
            ret = ret + '\\'
    ret = ret + c
    return ret
```

**Comment by allenh1** [comment]
That would do the job, but I would stronly prefer a more abstracted approach. If you want to escape it, you can add an argument to the method defaulting to `True`.
