### ISSUE TITLE
Implement argparse

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [allenh1/superflore#33]
An option to force the regeneration of *all* packages will be nice.

**Comment by allenh1** [comment]
That's what the `--all` flag does.

**Comment by tfoote** [comment]
It looks like this option is available but hard to discover. @allenh1  I'd recommend that you use argparse instead of manually parsing the arguments. It's quite helpful and will provide more expected command line interactions.

**Comment by allenh1** [comment]
That's probably a good idea. I'm too used to C, haha.

**Comment by allenh1** [comment]
Fixed, #39
