### ISSUE TITLE
Every single package attempt seems to pull the package.xml from an incorrect url and falls back

### ISSUE THREAD

**Issue by tfoote** [allenh1/superflore#46]
Like this: 

The first URL is missing the rosdistro between the `release` and package name and shouldn't have the version number: https://github.com/ros-gbp/gazebo_ros_pkgs-release/blob/release/lunar/gazebo_dev/package.xml

Or maybe should use the versioned one or just use the final one?
```
>>>> 17.5%: Successfully generated installer for package.
Failed to read package.xml file from url 'https://raw.github.com/ros-gbp/gazebo_ros_pkgs-release/release/gazebo_dev/2.7.2/package.xml': HTTP Error 404: Not Found
Trying to read from url 'https://raw.github.com/ros-gbp/gazebo_ros_pkgs-release/release/lunar/gazebo_dev/2.7.2-0/package.xml' instead
>>>> failed to parse website for package gazebo_dev
>>>> 17.7%: Successfully generated installer for package.
```

**Comment by allenh1** [comment]
That's the result of ros-infrastructure/rosdistro#99. The fix has been merged into master, but I don't think the package has been re-released yet.

**Comment by tfoote** [comment]
Thanks as a workaround I ran 
    $ pip install -U git+ssh://git@github.com/ros-infrastructure/rosdistro.git
inside my virtual env  and then this goes away.
